// Generated by CoffeeScript 1.7.1
(function() {
  var app;

  app = angular.module('app', ['selectAddress']);

  app.controller('appCtrl', function($scope) {
    $scope.p = '广西';
    $scope.c = '南宁市';
    $scope.a = '江南区';
    return $scope.d = '龙光普罗旺斯';
  });
  angular.bootstrap(document, ['app']);

}).call(this);

//# sourceMappingURL=index.map
